version: '3.4'

services:
  brewery.api:
    image: ${DOCKER_REGISTRY-}breweryapi
    build:
      context: .
      dockerfile: Services/Brewery/Brewery.API/Dockerfile
    depends_on:
      - sqldata
  
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest

  identity.ui:
    image: ${DOCKER_REGISTRY-}identityui
    build:
      context: .
      dockerfile: Services/Identity.UI/Dockerfile

